version: '3.8'

services:
  auditsphere-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auditsphere-ai
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://admin_audit:PasswordKuatAudit123!@100.72.19.38:5432/auditsphere
      - DIRECT_URL=postgresql://admin_audit:PasswordKuatAudit123!@100.72.19.38:5432/auditsphere
      - GEMINI_API_KEY=AIzaSyCzW7VqeuED4E7MJjggUOEePJJZ1mboEoM
